= XCP and FMI 3.0
:sectnums:
:sectnumlevels: 5
:toc: left
:toc-title: Contents
:toclevels: 5
:xrefstyle: short
:docinfo: shared
:docinfodir: docs
:stylesheet: docs/fmi-spec.css
:stem: latexmath
:source-highlighter: highlightjs
:nofooter:
:favicon: images/favicon.ico
:revdate: unreleased
:revnumber: 3.0
:icons: font

This layered standard defines, based on FMI 3.0, how to describe and implement XCP support for FMUs.

{empty} +
{empty}

Copyright (C) 2012-2022 The Modelica Association Project FMI.

This document is licensed under the Attribution-ShareAlike 4.0 International license.
The code is released under the 2-Clause BSD License.
The licenses text can be found in the https://raw.githubusercontent.com/modelica/fmi-standard/master/LICENSE.txt[LICENSE.txt] file that accompanies this distribution.

{empty}

== Introduction

=== Intend of this Document

FMI 3.0 was extended also with virtual Electronic Control Units (virtual ECUs) in mind.
Engineers can measure into ECUs using the XCP protocol and A2L variable descriptions:

[quote, ASAM e.V., https://www.asam.net/standards/detail/mcd-1-xcp/[ASAM MCD-1 XCP]]
____
The ASAM MCD-1 XCP (Universal Measurement and Calibration Protocol) standard defines a bus-independent, master-slave communication protocol to connect ECUs with calibration systems.
XCP is short for Universal Measurement and Calibration Protocol.
The primary purpose of XCP is to adjust internal parameters and acquire the current values of internal variables of an ECU.
The first letter X in XCP expresses the fact that the protocol is designed for a variety of bus systems.
The standard consists of a base standard, which describes memory-oriented protocol services without direct dependencies on specific bus systems.
Several associate standards contain the transport layer definitions for CAN, FlexRay, Ethernet (UDP/IP and TCP/IP), serial links (SPI and SCI) and USB.
____

This layered standard describes how an FMU advertises its XCP capabilities to importers and MCD tools using the XCP protocol.

=== Rough Outline of the Approach

The FMU implements an XCP slave which provides access to measurement and calibration variables of the virtual ECU and handles the communication protocol with the XCP master in the MCD tool.
The necessary information for an MCD tool is given in a description file which follows the https://www.asam.net/standards/detail/mcd-2-mc/[ASAM MCD-2 MC] standard (aka `A2L`, also `ASAP2`) and customarily carries the file extension `.a2l`.

[quote, ASAM e.V., https://www.asam.net/standards/detail/mcd-2-mc/[ASAM MCD-2 MC]]
____
ASAM MCD-2 MC (aka ASAP2) defines the description format of the internal ECU variables used in measurement and calibration.
Measurement & calibration systems (MC-systems) require this description for both the parameterization of scalar constants, curves and maps of the ECU software and for recording the system's response via measurement variables during real-time testing.
The description contains information about data types, dimensions, record layouts and memory locations of ECU variables.
The standard also describes how the variable values are converted into human-readable quantities and displayed in an MC-system.
____

=== Comments about this Approach

_[This layered standard will have no effect on the FMU interface, nor the C-API behavior._
_The XCP slave inside the FMU will most likely run in its own thread and leave the rest of the operation of the FMU unaffected._

_The XCP/A2L approach can not only be used for virtual ECUs, but also for plant models, if the FMU exporter generates an appropriate `A2L` file.]_

== Details

=== Structure of the FMU archive

A2L description files and other files needed for XCP support will be placed in the `extra` folder under the reverse domain name controlled by the MAP FMI: `/extra/org.modelica.fmi.layered_XCP`.
The folder structure is shown below.
Details are described in the following sections.

[[figure-fmi-layered-XCP-folder-structure]]
----
documentation
   layered_XCP{.txt,.html}          // Informal description how to use XCP/A2L for this FMU (optional).
extra/org.modelica.fmi.layered_XCP  // Contains files related to XCP/A2L
   <modelIdentifier>.a2l            // Variable description of a source code FMU (optional)
   x86_64-windows
      <modelIdentifier>.a2l         // Variable description for Windows on Intel 64-bit (optional)
   x86-linux
      <modelIdentifier>.a2l         // Variable description for Linux on Intel 32-bit (optional)
   aarch32-linux
      <modelIdentifier>.a2l         // Variable description for Linux on ARM 32-bit (optional)
   x86_64-darwin
      <modelIdentifier>.a2l         // Variable description for macOS (optional)
----

=== Documentation

When shipping an FMU with XCP/A2L support, it is recommended to provide the necessary information for the consumer in the file `documentation/layered_XCP.{txt|html}`.
For example, this concerns information how to build the final A2L file, if the FMU is delivered as source code.

=== A2L Description Files

The `A2L` description depends on the FMU binary, for example, regarding memory addresses, and byte order.
If an FMU archive contains multiple binaries for different platforms, the associated A2L files are placed into separate subfolders below `/extra/org.modelica.fmi.layered_XCP` following the same scheme as in the `/binaries` folder, see <<Structure of the FMU archive>>.

Note, that these `A2L` files are not intended to be downloaded to the simulator platform.
_[Any files that are required on the simulator shall be handled as defined by the FMI standard via the `/resource` folder.]_

`A2L` files may have a considerable size.
If size is a concern, it may be decided to supply just a single platform and `A2L` file with an FMU.

The root name of the A2L file shall be identical to the model identifier and is case sensitive, i.e. a variable description named `<modelIdentifier>.a2l` is associated with an FMU binary named `<modelIdentifier>.{dll,so}`.

All format versions of the `A2L` standard are allowed and it is the MCD tool's responsibility to handle each format version correctly.

This standard forbids the use of the `including mechanism` of additional `A2L` files to simplify complete extraction and copying of the `A2L` file to a location where it is accessible by the MCD tool.

The addresses in the A2L file are relative to the base address of the FMU binary loaded in the simulator.
The XCP slave implementation is responsible for translating the addresses to the physical addresses needed to access the variable values.

=== XCP Protocol Settings

The `A2L` description shall include `IF_DATA XCP` elements to help MCD tools to connect and interact with the XCP slave inside the FMU more reliably and without user interaction.
Parts of the `IF_DATA_XCP` description depend on the machine where the FMU binary is executed, for example, the IP address and port.

The default IP address used by the FMU exporter shall be `localhost`, i.e. `127.0.0.1`, which fits in many cases.
The requirement for the port number is, that it must be unique on the machine where the FMU binary is executed.
Typically, a certain range of ports is reserved for this purpose.
The FMU importer is responsible for checking if any conflicts of the defined IP addresses and port numbers occur in the context of the simulated system.

Sometimes it is necessary for the FMU importer to override the default IP address and/or port number which was assigned by the FMU exporter.
Therefore, the FMU model description shall contain two structural parameters which are used by the XCP slave during the configuration phase to setup the connection for the XCP protocol, see <<XCP Slave Implementation>>.

.XCP connection parameters
[[figure-xcp-connection-parameters]]
----
    IPAddress
        Description:  "IP address or host name of the machine where the FMU binary is executed"
        Type:         String
        Causality:    structuralParameter
        Variability:  fixed
        Start:        "127.0.0.1"

    XcpPortNumber
        Description:  "Port number where the XCP slave listens for XCP protocol commands"
        Type:         UInt16
        Causality:    structuralParameter
        Variability:  fixed
        Start:        <in the range of 32768 to 39999>
----

The consumer of an FMU is responsible for keeping all occurrences of the IP address and port number consistent, either by manual adjustment of the FMU model description and the A2L file, or with tool support.


=== XCP Slave Implementation

Preferably, the XCP service shall be started during `fmi3ExitConfigurationMode` and shut down during `fmi3Terminate` if the FMU has no explicit power-up signal to simplify user interactions between simulator and MCD tool.
If the FMU contains a virtual ECU with power-up control (K15), all build in OS and Basic Software services (including XCP) should follow normal power-up protocol.
The XCP service must run after `fmi3EnterInitializationMode` at the latest.

If the simulator puts the FMU in `Configuration Mode` and sets the structural parameters `IPAddress` and `XcpPortNumber` (see <<figure-xcp-connection-parameters>>), the XCP slave shall use those parameters to set up the communication connection for the XCP protocol.
After leaving `Configuration Mode` the XCP slave shall be responsive for XCP commands.
Thus, it is possible for the XCP master to perform calibration during the `Instantiated` state of the FMU, for example, to set parameters before entering `Initialization Mode`.
Note, that reading values of calculated variables, which depend on an initialization function is only possible after leaving the `Initialized` state with `fmi3ExitInitializationMode`.

If the XCP service is not started during `Configuration Mode`, because the simulator does not support structural parameters and therefore does not enter `Configuration Mode`, it must be started in `fmi3EnterInitializationMode` at the latest. In this case, it is not possible to perform calibration before the simulation is running.

_[The A2L/XCP standards allow to measure variables synchronously to different types of events._
_These so called measurement rasters are either time-based, angular-based, or non-deterministic, and are identified by a unique raster ID._
_The XCP service must be invoked with the defined raster ID in the thread which is executed for an event._
_Calibration and communication with the XCP master is typically performed in a background thread._
_The background thread must always be responsive to the XCP master within the defined communication timeout._
_Refer to the A2L/XCP standards for more information._

_The implementation of the XCP slave inside the FMU shall only use calls of the host OS, which leave the behavior of the FMU unaffected._
_This concerns, for example, host OS calls_
footnote:[The term 'host OS' means the OS where the FMU process is executed.
This could even be the OS inside a virtual machine connected to the simulator.]
_needed for creation of an own background thread, or for resolving variable addresses relative to the base address of the loaded FMU binary._
_Note, that blocking OS calls should be avoided, because they may have an effect on other parts of the simulator outside the FMU._

_<<XCP-Communication-via-IP-Stack>> shows a typical design where the XCP slave (in the FMU) communicates with the XCP master (in the MCD tool) using a separate network channel, e.g. the IP stack of the host OS._
_Thus, the communication of the XCP service is not mixed with the simulated network communication of the ECU wrapped in the FMU._
footnote:[The network communication of FMUs is described by another layered standard.
The details of network communication are out of scope here.]

_<<XCP-Communication-via-Virtual-ECU-COM-Stack>> shows an alternative design where the XCP slave communicates via the COM stack of the virtual ECU as in a real ECU._
_In this case, the simulator has to provide access to the simulated network communication for the MCD tool._
_This design may be chosen if the XCP slave implementation is already part of a level-3 ECU code to be tested._
footnote:[The same design could be used to access a diagnostic service, if it is implemented by the ECU code inside the FMU.]
]

.Direct communication of XCP master and XCP slave via the IP stack of the host OS
[#XCP-Communication-via-IP-Stack]
image::images/XCP-Communication-via-IP-Stack.svg[width=80%, align="center"]

.Communication of XCP master and XCP slave via the COM stack of the virtual ECU
[#XCP-Communication-via-Virtual-ECU-COM-Stack]
image::images/XCP-Communication-via-Virtual-ECU-COM-Stack.svg[width=80%, align="center"]


=== Source Code FMUs

For the special case when an FMU is delivered as target-independent source code (possibly with some libraries), a `raw A2L fragment` is placed directly into the `/extra/org.modelica.fmi.layered_XCP` folder.
The `raw A2L fragment` of a source code FMU is necessarily incomplete, because the details of the A2L description depend on the binary for the target platform, for example, regarding memory addresses, alignments, checksums, etc.

In the case of source code FMUs, the FMU exporter is responsible for providing the implementation of the XCP slave module.
The XCP slave must be invoked in the FMU code according to the defined measurement rasters and in the background as described in <<XCP Slave Implementation>>.

The FMU importer is responsible for building the FMU binary and creating the final A2L file by adjusting platform dependent information in the `raw A2L fragment`.
This concerns memory addresses, alignments, checksums, `IF_DATA_XCP` elements, etc.

If additional information for the build process and A2L creation is required, it should be provided by the FMU exporter in `documentation/layered_XCP.{txt|html}`.


=== Variable Visibility

The `modelDescription.xml` file publishes a certain set of variables and parameters.
The `A2L` file also publishes a set of FMU variables and parameters.
This standard expressly does not restrict the relationship between both sets of variables.

_[As a matter of fact, it is quite likely that the variables published in `modelDescription.xml` is a minimal set required for connectivity reasons._
_The `A2L` file might publish a much larger set of variables and parameters that the user can selectively choose to measure or calibrate._

_Note, that normally only variables in the memory segments owned by the main FMU binary `{.dll, .so}` are accessible by the XCP service, i.e. variables defined in source code modules and in statically linked libraries._
_Accessing variables in the memory of indirectly loaded dynamic libraries requires a special implementation which is out-of-scope for this layered standard._
_From the viewpoint of an MCD tool, the details of the variable access are transparent, i.e. this information is encapsulated in the A2L file.]_

=== Numeric Effects of XCP Access

While measurement of FMU internal variables does not have a numeric effect on the FMU, so called calibration does.
Calibration is the tuning of FMU internal parameters.
Such changes will affect the numeric behavior of the FMU.
If the FMU contains controller code, numeric stability or energy preservation laws are of lesser concern.
On the other hand, plant models offering XCP access for parameter calibration may introduce surprising numerical effects in solvers that might require proper handling, like resetting solvers with every XCP write action.

It is therefore necessary to synchronize XCP variable access (read and write) with the state of the FMU.
_[For instance is time not linear in Model Exchange and Intermediate Variable Access might also introduce surprising measurements in Co-Simulation._
_Appropriate care must be taken when to serve XCP master requests to ensure simulation and measurement integrity.]_
